---
general:
 buildTool: "npm"
service:
 buildToolVersion: "N16"
stages:
 Build:
  mavenExecuteStaticCodeChecks: false
  npmExecuteLint: false
 Additional Unit Tests:
  npmExecuteScripts: false
  karmaExecuteTests: false
 Acceptance:
  cloudFoundryDeploy: true
  cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
  cfOrg: "CLOUDCI_democicd"
  cfSpace: "biser-test"
  cfAppName: "hellohjajah"
  cfCredentialsId: "cf-technical-user"
  cfManifest: "manifest.yml"
  uiVeri5ExecuteTests: false
 Compliance:
  sonarExecuteScan: false
 Release:
  cloudFoundryDeploy: false
  tmsUpload: false
steps:
 artifactPrepareVersion:
  versioningType: "cloud_noTag"
 cloudFoundryDeploy:
  mtaDeployParameters: "-f --version-rule ALL"
